#!/usr/bin/env python3
"""Generate vendor/ulefone/gq5012bf1 makefiles from proprietary-files.txt."""

from __future__ import annotations

import os
from pathlib import Path
import re

DEVICE = "gq5012bf1"
VENDOR = "ulefone"
COPY_OUT = {
    "vendor": "$(TARGET_COPY_OUT_VENDOR)",
    "odm": "$(TARGET_COPY_OUT_ODM)",
    "product": "$(TARGET_COPY_OUT_PRODUCT)",
    "system_ext": "$(TARGET_COPY_OUT_SYSTEM_EXT)",
    "vendor_dlkm": "$(TARGET_COPY_OUT_VENDOR_DLKM)",
    "odm_dlkm": "$(TARGET_COPY_OUT_ODM_DLKM)",
    "system_dlkm": "$(TARGET_COPY_OUT_SYSTEM_DLKM)",
}


def build_top(device_dir: Path) -> Path:
    env = os.environ.get("ANDROID_BUILD_TOP")
    return Path(env).resolve() if env else device_dir.parents[2]


def entries(path: Path) -> list[str]:
    result: list[str] = []
    for line in path.read_text().splitlines():
        value = line.split("#", 1)[0].strip().lstrip("-")
        if not value:
            continue
        result.append(value.split(";", 1)[0].split(":", 1)[0])
    return result


def destination(entry: str) -> str:
    partition, relative = entry.split("/", 1)
    if partition == "system":
        if relative.startswith("system/"):
            relative = relative.removeprefix("system/")
        return f"$(TARGET_COPY_OUT_SYSTEM)/{relative}"
    return f"{COPY_OUT[partition]}/{relative}"


def module_name(entry: str) -> str:
    partition, relative = entry.split("/", 1)
    stem = Path(relative).parent.name or Path(relative).stem
    return re.sub(r"[^A-Za-z0-9_]", "_", f"gq5012bf1_{partition}_{stem}")


def app_import(entry: str) -> str:
    partition, relative = entry.split("/", 1)
    privileged = "/priv-app/" in f"/{relative}"
    specific = {
        "product": "    product_specific: true,\n",
        "system_ext": "    system_ext_specific: true,\n",
        "vendor": "    vendor: true,\n",
    }.get(partition, "")
    return (
        "android_app_import {\n"
        f"    name: \"{module_name(entry)}\",\n"
        f"    apk: \"proprietary/{entry}\",\n"
        "    presigned: true,\n"
        "    enforce_uses_libs: false,\n"
        f"    privileged: {str(privileged).lower()},\n"
        f"    filename: \"{Path(entry).name}\",\n"
        f"{specific}"
        "    dex_preopt: { enabled: false },\n"
        "}\n"
    )


def main() -> int:
    device_dir = Path(__file__).resolve().parent
    vendor_dir = build_top(device_dir) / "vendor" / VENDOR / DEVICE
    vendor_dir.mkdir(parents=True, exist_ok=True)
    proprietary = entries(device_dir / "proprietary-files.txt")
    aosp_replaced = set(entries(device_dir / "aosp-replaced-files.txt"))
    # Stock oat artifacts are build-specific and must not be transplanted.
    integrated = [
        entry for entry in proprietary
        if Path(entry).suffix not in {".odex", ".vdex", ".art"}
        and Path(entry).name not in {"build.prop", "default.prop", "prop.default"}
        and entry not in aosp_replaced
    ]
    vintf = [entry for entry in integrated if "/etc/vintf/" in entry]
    # VINTF is assembled by the build system from source XML, never copied as
    # opaque PRODUCT_COPY_FILES metadata.
    integrated = [entry for entry in integrated if entry not in vintf]
    # uSmartCamera is a downloadable stock resource, not an installed package.
    # Keep it accounted in proprietary-files.txt but do not silently install it.
    apks = [entry for entry in integrated if entry.endswith(".apk") and "/media/resource/Download/" not in entry]
    copies = [entry for entry in integrated if not entry.endswith(".apk")]

    bp = [
        "// Generated by device/ulefone/gq5012bf1/setup-makefiles.py",
        "soong_namespace {}",
        "",
    ]
    bp.extend(app_import(entry) for entry in apks)
    (vendor_dir / "Android.bp").write_text("\n".join(bp))
    vendor_manifests = [
        entry for entry in vintf
        if entry == "vendor/etc/vintf/manifest.xml" or entry.startswith("vendor/etc/vintf/manifest/")
    ]
    odm_dsds = [entry for entry in vintf if entry.endswith("/manifest_dsds.xml")]
    board_lines = [
        "# Generated by setup-makefiles.py",
        f"PRODUCT_SOONG_NAMESPACES += vendor/{VENDOR}/{DEVICE}",
        "",
    ]
    if vendor_manifests:
        board_lines.append("DEVICE_MANIFEST_FILE += \\")
        for index, entry in enumerate(vendor_manifests):
            continuation = " \\" if index != len(vendor_manifests) - 1 else ""
            board_lines.append(f"    vendor/{VENDOR}/{DEVICE}/proprietary/{entry}{continuation}")
        board_lines.append("")
    if odm_dsds:
        board_lines.append("# Retail hardware is dual-SIM; alternate SS/TSTS/QSQS manifests remain evidence only.")
        board_lines.append("ODM_MANIFEST_FILES += \\")
        for index, entry in enumerate(odm_dsds):
            continuation = " \\" if index != len(odm_dsds) - 1 else ""
            board_lines.append(f"    vendor/{VENDOR}/{DEVICE}/proprietary/{entry}{continuation}")
        board_lines.append("")
    (vendor_dir / "BoardConfigVendor.mk").write_text("\n".join(board_lines))

    lines = [
        "# Generated by device/ulefone/gq5012bf1/setup-makefiles.py",
        "# Do not edit by hand; update proprietary-files.txt and regenerate.",
        "PRODUCT_COPY_FILES += \\",
    ]
    for index, entry in enumerate(copies):
        continuation = " \\" if index != len(copies) - 1 else ""
        lines.append(
            f"    vendor/{VENDOR}/{DEVICE}/proprietary/{entry}:{destination(entry)}{continuation}"
        )
    if apks:
        lines += ["", "PRODUCT_PACKAGES += \\"]
        for index, entry in enumerate(apks):
            continuation = " \\" if index != len(apks) - 1 else ""
            lines.append(f"    {module_name(entry)}{continuation}")
    lines += ["", f"PRODUCT_SOONG_NAMESPACES += vendor/{VENDOR}/{DEVICE}", ""]
    (vendor_dir / f"{DEVICE}-vendor.mk").write_text("\n".join(lines))
    print(
        f"generated vendor makefiles for {len(copies)} copied files and "
        f"{len(apks)} imported APKs; {len(aosp_replaced)} stock paths use "
        f"AOSP replacements in {vendor_dir}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
